name: build

on:
  push:
  pull_request:
jobs:
  macos:
    strategy:
      fail-fast: false
      matrix:
        macos:
          - 14
        xcode:
          - latest-stable
    runs-on: macos-${{ matrix.macos }}
    steps:
      - name: Select Xcode version
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: ${{ matrix.xcode }}
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: |
            xcodebuild -scheme "Chess" -sdk iphonesimulator -destination "name=iPhone 15" clean build
